version: '3.8'

services:
  focus:
    image: ghcr.io/inter-hubly/focus:${ENVIRONMENT}
    container_name: focus
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - REACT_APP_KEEPER_API_URL=${REACT_APP_KEEPER_API_URL}
      - REACT_APP_ENVIRONMENT_PULSE_WEBSOCKET=${REACT_APP_ENVIRONMENT_PULSE_WEBSOCKET}
    ports:
      - "3011:80"
    networks:
      - hubly-network
    depends_on:
      - linker
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
  
  keeper:
    image: ghcr.io/inter-hubly/keeper:${ENVIRONMENT}
    container_name: keeper
    environment:
      - ENVIRONMENT_PORT=8081
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
      - ENVIRONMENT_HASH_ENCRYPT=${ENVIRONMENT_HASH_ENCRYPT}
      - ENVIRONMENT_MONGO_DATABASE=${ENVIRONMENT_MONGO_DATABASE}
      - ENVIRONMENT_MONGO_HOST=${ENVIRONMENT_MONGO_HOST}
    
    ports:
      - "8081:8081"
      - "8091:8091"
    networks:
      - hubly-network
    depends_on:
      - linker
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always

  linker:
    image: ghcr.io/inter-hubly/linker:${ENVIRONMENT}
    container_name: linker
    environment:
      - ENVIRONMENT_PORT=8085
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
      - ENVIRONMENT_LINKER_HOST=${ENVIRONMENT_LINKER_HOST}
      - ENVIRONMENT_KEEPER_HOST=${ENVIRONMENT_KEEPER_HOST}
      - ENVIRONMENT_WEBHOOK_HOST=${ENVIRONMENT_WEBHOOK_HOST}
      - ENVIRONMENT_PULSE_HOST=${ENVIRONMENT_PULSE_HOST}
      - ENVIRONMENT_MONGO_DATABASE=${ENVIRONMENT_MONGO_DATABASE}
      - ENVIRONMENT_MONGO_HOST=${ENVIRONMENT_MONGO_HOST}

    ports:
      - "8085:8085"
      - "8095:8095"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always

  pulse:
    image: ghcr.io/inter-hubly/pulse:${ENVIRONMENT}
    container_name: pulse
    environment:
      - ENVIRONMENT_PORT=8082
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
      - ENVIRONMENT_LINKER_HOST=${ENVIRONMENT_LINKER_HOST}
      - ENVIRONMENT_KEEPER_HOST=${ENVIRONMENT_KEEPER_HOST}
      - ENVIRONMENT_WEBHOOK_HOST=${ENVIRONMENT_WEBHOOK_HOST}
      - ENVIRONMENT_PULSE_HOST=${ENVIRONMENT_PULSE_HOST}
      - ENVIRONMENT_MONGO_DATABASE=${ENVIRONMENT_MONGO_DATABASE}
      - ENVIRONMENT_MONGO_HOST=${ENVIRONMENT_MONGO_HOST}
    
    ports:
      - "8082:8082"
      - "8092:8092"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always

  webhook:
    image: ghcr.io/inter-hubly/webhook:${ENVIRONMENT}
    container_name: webhook
    environment:
      - ENVIRONMENT_PORT=8080
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
      - ENVIRONMENT_LINKER_HOST=${ENVIRONMENT_LINKER_HOST}
      - ENVIRONMENT_KEEPER_HOST=${ENVIRONMENT_KEEPER_HOST}
      - ENVIRONMENT_WEBHOOK_HOST=${ENVIRONMENT_WEBHOOK_HOST}
      - ENVIRONMENT_PULSE_HOST=${ENVIRONMENT_PULSE_HOST}
      - ENVIRONMENT_WHATSAPP_SECRET=${ENVIRONMENT_WHATSAPP_SECRET}
      - ENVIRONMENT_MONGO_DATABASE=${ENVIRONMENT_MONGO_DATABASE}
      - ENVIRONMENT_MONGO_HOST=${ENVIRONMENT_MONGO_HOST}
    
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - hubly-network
    depends_on:
      - focus
      - keeper
      - linker
      - pulse
      - webhook
      - rabbitmq
      - elasticsearch
      - kibana
      - postgres
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5671:5672"
      - "15671:15672"
      - "15692:15692"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - kibana
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_prometheus &&
          rabbitmq-server"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - hubly-network
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=hubly

    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hubly-network
    depends_on:
      - rabbitmq

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: postgres://postgres:mypass@postgres:5432/hubly?sslmode=disable
    depends_on:
      - postgres
    networks:
      - hubly-network
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DATASOURCES_DEFAULT_NAME: prometheus
      GF_DATASOURCES_DEFAULT_TYPE: prometheus
      GF_DATASOURCES_DEFAULT_URL: http://prometheus:9090
      GF_DATASOURCES_DEFAULT_ACCESS: proxy
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - hubly-network
    depends_on:
      - prometheus
  
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hubly-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
  
  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    environment:
      MONGODB_URI: mongodb://mongodb:27016
    ports:
      - "9216:9216"
    depends_on:
      - mongodb
    networks:
      - hubly-network

#  sonarqube:
#    image: sonarqube:lts-community
#    depends_on:
#      - sonar_db
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
#      SONAR_JDBC_USERNAME: sonar
#      SONAR_JDBC_PASSWORD: sonar
#    ports:
#      - "9001:9000"
#    volumes:
#      - sonarqube_conf:/opt/sonarqube/conf
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_logs:/opt/sonarqube/logs
#      - sonarqube_temp:/opt/sonarqube/temp
#
#  sonar_db:
#    image: postgres:13
#    environment:
#      POSTGRES_USER: sonar
#      POSTGRES_PASSWORD: sonar
#      POSTGRES_DB: sonar
#    volumes:
#      - sonar_db:/var/lib/postgresql
#      - sonar_db_data:/var/lib/postgresql/data

volumes:
  esdata:
  pgdata:
  grafana_data:
  mongo_data:
#  sonarqube_conf:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_logs:
#  sonarqube_temp:
#  sonar_db:
#  sonar_db_data:
    
networks:
  hubly-network:
    driver: bridge
