version: '3.8'

x-common-env: &common-env
  ENVIRONMENT: development
  ENVIRONMENT_ELASTICSEARCH_HOST: http://localhost:9200
  ENVIRONMENT_REDIS_HOST: localhost:6379
  ENVIRONMENT_REDIS_DATABASE: 0
  ENVIRONMENT_AMPQ_HOST: amqp://guest:guest@localhost:5672/
  ENVIRONMENT_MONGO_HOST: mongodb://localhost:27017
  ENVIRONMENT_MONGO_DATABASE: hubly

services:
  keeper:
    image: ghcr.io/inter-hubly/keeper:development
    container_name: keeper
    environment:
      <<: *common-env
      ENVIRONMENT_PORT: 8081
      ENVIRONMENT_PGSQL_HOST: postgres://postgres:frajolinha202@localhost:5432/hubly
      ENVIRONMENT_HASH_ENCRYPT:
    network_mode: "host"
    restart: always

  linker:
    image: ghcr.io/inter-hubly/linker:development
    container_name: linker
    environment:
      <<: *common-env
      ENVIRONMENT_PORT: 8085
      ENVIRONMENT_PGSQL_HOST: postgres://postgres:frajolinha202@localhost:5432/hubly
      ENVIRONMENT_LINKER_HOST: linker
      ENVIRONMENT_KEEPER_HOST: keeper
      ENVIRONMENT_WEBHOOK_HOST: webhook
      ENVIRONMENT_PULSE_HOST: http://localhost:8082
    network_mode: "host"
    restart: always

  pulse:
    image: ghcr.io/inter-hubly/pulse:development
    container_name: pulse
    environment:
      <<: *common-env
      ENVIRONMENT_PORT: 8082
      ENVIRONMENT_PGSQL_HOST: postgres://postgres:frajolinha202@localhost:5432/hubly
      ENVIRONMENT_LINKER_HOST: linker
      ENVIRONMENT_KEEPER_HOST: keeper
      ENVIRONMENT_WEBHOOK_HOST: webhook
      ENVIRONMENT_PULSE_HOST: http://localhost:8082
    network_mode: "host"
    restart: always

  webhook:
    image: ghcr.io/inter-hubly/webhook:development
    container_name: webhook
    environment:
      <<: *common-env
      ENVIRONMENT_PORT: 8080
      ENVIRONMENT_PGSQL_HOST: postgres://postgres:frajolinha202@localhost:5431/hubly
      ENVIRONMENT_LINKER_HOST: linker
      ENVIRONMENT_KEEPER_HOST: keeper
      ENVIRONMENT_WEBHOOK_HOST: webhook
      ENVIRONMENT_PULSE_HOST: http://localhost:8082
      ENVIRONMENT_WHATSAPP_SECRET: hubly
    network_mode: "host"
    restart: always

networks:
  hubly-network:
