version: '3.8'
# docker-compose -f docker-compose.services.yml up -d
services:
  keeper:
    image: ghcr.io/inter-hubly/keeper:${ENVIRONMENT}
    container_name: keeper
    environment:
      - ENVIRONMENT_PORT=8081
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8081:8081"
    networks:
      - hubly-network
    restart: always

  linker:
    image: ghcr.io/inter-hubly/linker:${ENVIRONMENT}
    container_name: linker
    environment:
      - ENVIRONMENT_PORT=8085
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8085:8085"
    networks:
      - hubly-network
    restart: always

  pulse:
    image: ghcr.io/inter-hubly/pulse:${ENVIRONMENT}
    container_name: pulse
    environment:
      - ENVIRONMENT_PORT=8082
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8082:8082"
    networks:
      - hubly-network
    restart: always

  webhook:
    image: ghcr.io/inter-hubly/webhook:${ENVIRONMENT}
    container_name: webhook
    environment:
      - ENVIRONMENT_PORT=8080
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8080:8080"
    networks:
      - hubly-network
    restart: always

networks:
  hubly-network:
