version: '3.8'

services:
  keeper:
    image: ghcr.io/inter-hubly/keeper:${ENVIRONMENT}
    container_name: keeper
    environment:
      - ENVIRONMENT_PORT=8081
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8081:8081"
    networks:
      - hubly-network
    depends_on:
      - linker
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always

  linker:
    image: ghcr.io/inter-hubly/linker:${ENVIRONMENT}
    container_name: linker
    environment:
      - ENVIRONMENT_PORT=8085
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8085:8085"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always

  pulse:
    image: ghcr.io/inter-hubly/pulse:${ENVIRONMENT}
    container_name: pulse
    environment:
      - ENVIRONMENT_PORT=8082
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8082:8082"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always
    
  webhook:
    image: ghcr.io/inter-hubly/webhook:${ENVIRONMENT}
    container_name: webhook
    environment:
      - ENVIRONMENT_PORT=8080
      - ENVIRONMENT=${ENVIRONMENT}
      - ENVIRONMENT_APPID=${ENVIRONMENT_APPID}
      - ENVIRONMENT_ELASTICSEARCH_HOST=${ENVIRONMENT_ELASTICSEARCH_HOST}
      - ENVIRONMENT_REDIS_HOST=${ENVIRONMENT_REDIS_HOST}
      - ENVIRONMENT_REDIS_DATABASE=${ENVIRONMENT_REDIS_DATABASE}
      - ENVIRONMENT_AMPQ_HOST=${ENVIRONMENT_AMPQ_HOST}
      - ENVIRONMENT_PGSQL_HOST=${ENVIRONMENT_PGSQL_HOST}
    ports:
      - "8080:8080"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - postgres
      - kibana
      - rabbitmq
    restart: always
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5671:5672"
      - "15671:15672"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - hubly-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - hubly-network
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=hubly

    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hubly-network
    depends_on:
      - rabbitmq

volumes:
  esdata:
  pgdata:

networks:
  hubly-network:
